import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <h1 className="text-5xl font-bold">Home</h1>
    </main>
  );
}
